{{ if .Values.gw.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "brigade.gw.fullname" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    role: gateway
    type: github
spec:
  type: {{ .Values.gw.service.type }}
  ports:
  - port: {{ .Values.gw.service.externalPort }}
    targetPort: {{ .Values.gw.service.internalPort }}
    protocol: TCP
    name: {{ .Values.gw.service.name }}
  selector:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    role: gateway
    type: github
{{ end }}
